#pragma once

#define IRPPROXY_DEVICE 0x8000
#define IOCTL_SELECT_TARGET CTL_CODE(IRPPROXY_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_STOP_MONITORING CTL_CODE(IRPPROXY_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACESS)
#define IOCTL_QUERY_PROXIED_IRP CTL_CODE(IRPPROXY_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)
