#pragma once

#define IRPPROXY_DEVICE 0x8000
#define IOCTL_HOOK_TARGET CTL_CODE(IRPPROXY_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_UNHOOK_TARGET CTL_CODE(IRPPROXY_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_QUERY_PROXIED_IRP CTL_CODE(IRPPROXY_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)

#define MAX_PATH 260
